image: maven:3-jdk-11

cache:
  key: "$CI_JOB_NAME"
  paths:
    - .m2/repository

stages:
  - build
  - deploy

maven-build:
  tags:
    - build
  stage: build
  script:
    - mvn -Pproduction spring-boot:build-image -DskipTests -Dspring.boot.build-image.imageName=jalin-backend
  only:
    - master

deploy-development:
  tags:
    - development
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - develop

deploy-production:
  tags:
    - production
  stage: deploy
  script:
    - source /home/gitlab-runner/jalin.env
    - docker-compose down
    - docker image prune -a -f
    - docker-compose up -d
  only:
    - master
