image: maven:3-jdk-11

cache:
  key: "$CI_JOB_NAME"
  paths:
    - .m2/repository

stages:
  - build
  - deploy

maven-build:
  tags:
    - build
  stage: build
  script:
    - mvn -Pproduction -DskipTests spring-boot:build-image
  only:
    - master

deploy-development:
  tags:
    - development
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - develop

deploy-production:
  tags:
    - production
  stage: deploy
  script:
    - docker tag jalin-app-backend:0.0.1-SNAPSHOT jalin-app-backend:latest
    - docker-compose down
    - docker-compose up -d
    - docker image prune -a -f
  only:
    - master
