version: '3.9'
services:
  core:
    restart: on-failure
    image: kristiansandratama/jalin:latest
    ports:
    - 8888:8080
    environment:
      - JDBC_DATABASE_URL=${JDBC_DATABASE_URL_CORE}
      - JDBC_DATABASE_USERNAME=${JDBC_DATABASE_USERNAME}
      - JDBC_DATABASE_PASSWORD=${JDBC_DATABASE_PASSWORD}
  backend:
    restart: on-failure
    depends_on:
      - core
    image: jalin-app-backend:0.0.1-SNAPSHOT
    ports:
    - 8889:8080
    environment:
      - JDBC_DATABASE_URL=${JDBC_DATABASE_URL}
      - JDBC_DATABASE_USERNAME=${JDBC_DATABASE_USERNAME}
      - JDBC_DATABASE_PASSWORD=${JDBC_DATABASE_PASSWORD}
      - RESOURCE_SERVER_URL=${RESOURCE_SERVER_URL}
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}