version: '3.9'
services:
  core:
    restart: on-failure
    image: kristiansandratama/jalin:latest
    ports:
    - 8888:8080
    env_file:
      - /home/gitlab-runner/jalin.env
  backend:
    restart: on-failure
    depends_on:
      - core
    image: jalin-app-backend:latest
    ports:
    - 8889:8080
    env_file:
      - /home/gitlab-runner/jalin.env